### ISSUE TITLE
UI 개선이 필요할 듯합니다

### ISSUE THREAD

**Issue by ohijiho** [CSNE/CampusNavi#21]
name으로만 장소를 식별하는 기존 방식에서는 제약이 발생
장소를 실제 vertex로 가져야 장소를 좀 더 다양한 방식으로 지정할 수 있음
장소를 현재 위치나 지도 상의 위치로 지정할 수 있어야 함

기존의 search와 nearby로 나눈 ui에서는 위와 같은 기능을 구현하기 어려움, 개선 필요

search와 nearby를 합쳐서 길찾기 같은걸로 두고
자동설정, 바꾸기, 시간, 그대로 둠

출발지 도착지를
1. 검색
2. 지도에서 찍기
3. 가장 가까운 무언가 (place)
4. 현재 위치
5. vertex group ex)공A (place)

3, 5는 내부 작동방식은 같지만 사용자가 보기엔 달라야 할 것 같음
검색은 중간 문자열을 입력해도 검색이 되면 좋을 듯, 이 경우 검색을 따로 구현해야 함

출발지 또는 도착지를 설정시, 그에 해당하는 vertex 또는 array를 저장하고, 출발지 도착지 입력란에 적절한 문자열을 표시

구체적인 ui 작동은 생각해봐야 할 듯
한가지 방법은
입력란을 select 컨트롤과 디비전으로 구성하고 select에서 입력방법을 선택하면 디비전 부분에 해당하는 입력란이 나타남
지도에서 찍는 경우는 지도를 강조표시하고 지도를 클릭하면 완료
입력하는 중에는 취소버튼이 있어야 함

**Comment by CSNE** [comment]
f5d990dda948e85637b387e0a871a20338530729
